all:
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/netology
    ansible_python_interpreter: /usr/bin/python3    
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local  
    masters:
      hosts:
        master0:
          ansible_host: 158.160.98.6
          internal_ip: 10.0.1.34
          external_ip: 158.160.98.6
    workers:
      hosts:
        worker0:
          ansible_host: 158.160.57.7
          internal_ip: 10.0.1.17
          external_ip: 158.160.57.7
        worker1:
          ansible_host: 158.160.53.125
          internal_ip: 10.0.1.26
          external_ip: 158.160.53.125
