all:
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/netology
    ansible_python_interpreter: /usr/bin/python3    
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local  
    masters:
      hosts:
        master0:
          ansible_host: 89.169.159.132
          internal_ip: 10.0.1.16
          external_ip: 89.169.159.132
    workers:
      hosts:
        worker0:
          ansible_host: 46.21.244.173
          internal_ip: 10.0.1.22
          external_ip: 46.21.244.173
        worker1:
          ansible_host: 130.193.38.21
          internal_ip: 10.0.1.15
          external_ip: 130.193.38.21
