apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-vol
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница APP</title>
    </head>
    <body>
      <h1>Контент передан через ConfigMap</h1>
    </body>
    </html>
