---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-vol2
  namespace: app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница APP ver 1.2</title>
    </head>
    <body>
      <h1>Прмер, как реализуется канареечный деплоймент</h1>
      <h2>Это <b>новая</b> версия приложения 1.2</h2>      
    </body>
    </html>
