cluster_init: true
cluster_name: NetologyK8S-1
k8s_cluster_release: 1.34
k8s_cluster_version: 1.34.2
k8s_package_version: 1.34.2-1.1
kubectl_version: 1.34.2
helm_version: 3.12.0
pod_cidr: 10.244.0.0/16
cri: containerd
admin_host_user: odv
config_folder: ~/.kube
