all:
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/netology
    ansible_python_interpreter: /usr/bin/python3    
  children:
    control:
      hosts:
        localhost:
          ansible_connection: local  
    masters:
      hosts:
        master0:
          ansible_host: 158.160.126.82
          internal_ip: 10.0.1.34
          external_ip: 158.160.126.82
    workers:
      hosts:
        worker0:
          ansible_host: 178.154.220.82
          internal_ip: 10.0.1.32
          external_ip: 178.154.220.82
        worker1:
          ansible_host: 178.154.222.99
          internal_ip: 10.0.1.20
          external_ip: 178.154.222.99
